### ISSUE TITLE
hiding service code may need to modify

### ISSUE THREAD

**Issue by wineggdrop** [bytecode77/r77-rootkit#138]
https://github.com/user-attachments/assets/6e476180-012e-48d3-84f7-982bac992bc3

test.exe uses EnumServicesStatusExW to retrieve service record.
test.exe /normal    using the api returnd dwEntried to list all the service record
test.exe /force       ignore the dwEntried and walk through the buffer to list all the service record

$77svc happens to be the last service(latest installed),so the walk through method can find the hidden service.Therefore,for the last service to hide,it's better to set the last record to zero)

Moreover,it would be better to add the ANSI version of api for hiding service since most 3rd parth apps use ANSI version of EnumServicesStatusExA  or EnumServicesStatusA.

**Comment by bytecode77** [comment]
You have a thing for buffer read overflows? ;)

I never considered it a usecase, because processing data that's still inside the buffer but exceeds the reported count is in and of itself dangerous. You would do this in search of a rootkit, I guess...? Either way, there are indicators to detect r77 more easily, such as the existence of the control pipe. The rootkit hides from the user and AV, but not from debuggers or reverse engineers. So, yes, this is theoretically a scenario. But where would this practically surface?

I even documented out of bounds reads as "Out of scope" (section 5.6 Bug Reports). Note, that I put this statement there back in 2021; I didn't include it recently.

On the subject of ANSI methods like `EnumService*A` - you said that most 3rd party tools use these instead of the unicode ones? I honestly had trouble finding any tool that uses the ANSI variants, so I didn't implement them. Can you point me to real-world tools that call the ANSI variants? Then I would love to implement these.

**Comment by wineggdrop** [comment]
The 3rd party toolsI mentioned mostly from underground,which has no official download and pretty easy to code in different program language using different API to get the job done.To counter windows build-in or famous tools,hooking the unicode version of API is sufficient,hooking the ansi version api just to counter the unknown tools,which can leave it to the user and it's pretty easy coz only   need to modify the unicode struture to the ansi one.

I wouldn't consider buffer data search is dangous since I am use malloc or HeapAlloc to allocate the memory for the required buffer to complete the   EnumServicesStatusExW call,which means I know the starting,ending address and the size of the buffer.

**Comment by bytecode77** [comment]
I'm going to implement it, because it's reasonable to not leave out the ANSI implementation. Might be a week or two before I can really sit down and get to it, but I'll let you know when I'm done!

**Comment by bytecode77** [comment]
I have implemented the hook for `EnumServicesStatusExA`. Could you check out the dev branch, compile and test it against the aforementioned tools?

Since I can't test with those, I copied the code you posted above, converted the calls to their ANSI equivalents, and used it for testing. It works with the new hook, however the "service walking" routine is odd. It doesn't check the returned count, but rather "walks" the services list until a NULL pointer is found (if i read the code correctly). This results in the last entry being duplicated, or if it's hidden, it will be shown.

Is this the issue you were talking about when you asked me to erase memory of hidden entries? Usually this problem should only surface if the implementation is incorrect, like the above. It actually gets problematic, if some well known underground tools are implemented that way, resulting in entry duplication, or hidden entries that become visible. Is this the case?

Either way, do you think you could mail me the tools you were talking about so I have something real to test on? And please let me know about the coverage of the `EnumServicesStatusExA` hook implementation, specifically whether further ANSI hooks need to be implemented.

**Comment by wineggdrop** [comment]
those tools use EnumServicesStatusExA or EnumServicesStatusA to list the service,the branch code still can't prevent EnumServicesStatusA to list the hidden service(EnumServicesStatusExA works fine and the hidden service remains hidden).

**Comment by wineggdrop** [comment]
it works without ant issue

**Comment by bytecode77** [comment]
Allright, so I've released Version **1.7.2** with the additional hooks :)
